export const mockCrops = [
  {
    _id: "1",
    name: "Wheat",
    localName: "Gehu",
    scientificName: "Triticum aestivum",
    category: "grain",
    season: "rabi",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600",
    description: "Wheat is a staple cereal crop grown widely across North India during the rabi season.",
    growingGuide: { soilType: "Loamy, well-drained", phRange: "6.5 - 7.5", temperature: "20°C - 25°C", rainfall: "75-100 cm annually" },
    fertilizerGuide: [
      { name: "Urea", quantity: "100 kg/acre", timing: "At sowing + 25 days after" },
      { name: "DAP", quantity: "50 kg/acre", timing: "At sowing" },
    ],
    irrigationGuide: { numberOfIrrigations: 5, intervalDays: 20, criticalStages: "Crown root initiation, flowering, grain filling" },
    diseaseManagement: [
      { disease: "Rust", prevention: "Use resistant varieties, avoid excess nitrogen", treatment: "Spray Propiconazole 25% EC" },
    ],
    harvestInfo: { harvestTime: "March - April, when crop turns golden yellow", yieldEstimate: "40-50 quintals/hectare" },
  },
  {
    _id: "2",
    name: "Paddy (Rice)",
    localName: "Dhan",
    scientificName: "Oryza sativa",
    category: "grain",
    season: "kharif",
    image: "https://images.pexels.com/photos/5188728/pexels-photo-5188728.jpeg",
    description: "Rice is the primary kharif crop, requiring waterlogged fields for most of its growth cycle.",
    growingGuide: { soilType: "Clayey, water-retentive", phRange: "5.5 - 6.5", temperature: "25°C - 35°C", rainfall: "100-200 cm annually" },
    fertilizerGuide: [
      { name: "Urea", quantity: "120 kg/acre", timing: "Split in 3 doses" },
      { name: "Potash", quantity: "40 kg/acre", timing: "At transplanting" },
    ],
    irrigationGuide: { numberOfIrrigations: 12, intervalDays: 7, criticalStages: "Tillering, panicle initiation, flowering" },
    diseaseManagement: [
      { disease: "Blast", prevention: "Avoid excess nitrogen, proper spacing", treatment: "Spray Tricyclazole" },
    ],
    harvestInfo: { harvestTime: "October - November", yieldEstimate: "50-60 quintals/hectare" },
  },
  {
    _id: "3",
    name: "Mustard",
    localName: "Sarson",
    scientificName: "Brassica juncea",
    category: "cash crop",
    season: "rabi",
    image: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=600",
    description: "Mustard is grown for its oil-rich seeds, popular in Rajasthan and Haryana.",
    growingGuide: { soilType: "Sandy loam", phRange: "6.0 - 7.5", temperature: "10°C - 25°C", rainfall: "25-40 cm annually" },
    fertilizerGuide: [{ name: "Sulphur", quantity: "20 kg/acre", timing: "At sowing" }],
    irrigationGuide: { numberOfIrrigations: 2, intervalDays: 30, criticalStages: "Flowering, pod formation" },
    diseaseManagement: [{ disease: "White Rust", prevention: "Crop rotation, resistant varieties", treatment: "Spray Mancozeb" }],
    harvestInfo: { harvestTime: "February - March", yieldEstimate: "8-10 quintals/hectare" },
  },
  {
    _id: "4",
    name: "Moong (Green Gram)",
    localName: "Moong",
    scientificName: "Vigna radiata",
    category: "pulse",
    season: "zaid",
    image: "https://images.pexels.com/photos/37924404/pexels-photo-37924404.jpeg",
    description: "A short-duration pulse crop, excellent for improving soil fertility through nitrogen fixation.",
    growingGuide: { soilType: "Well-drained sandy loam", phRange: "6.2 - 7.2", temperature: "25°C - 35°C", rainfall: "60-75 cm annually" },
    fertilizerGuide: [{ name: "DAP", quantity: "25 kg/acre", timing: "At sowing" }],
    irrigationGuide: { numberOfIrrigations: 3, intervalDays: 15, criticalStages: "Flowering, pod filling" },
    diseaseManagement: [{ disease: "Yellow Mosaic Virus", prevention: "Use resistant varieties, control whitefly", treatment: "Spray Imidacloprid" }],
    harvestInfo: { harvestTime: "60-75 days after sowing", yieldEstimate: "6-8 quintals/hectare" },
  },
  {
    _id: "5",
    name: "Turmeric",
    localName: "Haldi",
    scientificName: "Curcuma longa",
    category: "spice",
    season: "kharif",
    image: "https://images.pexels.com/photos/12122270/pexels-photo-12122270.jpeg",
    description: "A high-value spice crop, valued for its rhizomes used in cooking and medicine.",
    growingGuide: { soilType: "Well-drained loamy", phRange: "5.5 - 7.5", temperature: "20°C - 30°C", rainfall: "150-200 cm annually" },
    fertilizerGuide: [{ name: "FYM (Farm Yard Manure)", quantity: "10 tonnes/acre", timing: "Before planting" }],
    irrigationGuide: { numberOfIrrigations: 15, intervalDays: 10, criticalStages: "Rhizome development" },
    diseaseManagement: [{ disease: "Rhizome Rot", prevention: "Well-drained soil, avoid waterlogging", treatment: "Drench with Copper Oxychloride" }],
    harvestInfo: { harvestTime: "210-270 days after planting", yieldEstimate: "200-250 quintals/hectare" },
  },
  {
    _id: "6",
    name: "Mango",
    localName: "Aam",
    scientificName: "Mangifera indica",
    category: "fruit",
    season: "zaid",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600",
    description: "India's most popular fruit crop, requiring years to mature but yielding for decades once established.",
    growingGuide: { soilType: "Deep, well-drained alluvial", phRange: "5.5 - 7.5", temperature: "24°C - 30°C", rainfall: "75-250 cm annually" },
    fertilizerGuide: [{ name: "NPK Mix", quantity: "1-2 kg/tree", timing: "Twice a year" }],
    irrigationGuide: { numberOfIrrigations: 8, intervalDays: 15, criticalStages: "Flowering, fruit set" },
    diseaseManagement: [{ disease: "Anthracnose", prevention: "Prune for airflow, avoid overhead watering", treatment: "Spray Carbendazim" }],
    harvestInfo: { harvestTime: "April - June (seasonal)", yieldEstimate: "8-10 tonnes/hectare (mature orchard)" },
  },
];