// dummy pest data, matches pest.model.js (name, type, affectedCrops, symptoms, treatment, prevention, image)

export const mockPests = [
  {
    _id: "1",
    name: "Aphid",
    type: "insect",
    affectedCrops: ["Wheat", "Mustard", "Cotton"],
    image: "https://placehold.co/600x400/D97757/ffffff?text=Aphid",
    symptoms: "Curling and yellowing of leaves, sticky honeydew residue, stunted plant growth, presence of small green or black insects clustered on stems and leaf undersides.",
    treatment: "Spray Imidacloprid 17.8% SL at 0.3ml/litre water, or use Neem oil spray for organic control. Repeat after 10 days if infestation persists.",
    prevention: "Encourage natural predators like ladybirds, avoid excess nitrogen fertilizer, monitor fields weekly during early growth stages.",
  },
  {
    _id: "2",
    name: "Wheat Rust",
    type: "fungus",
    affectedCrops: ["Wheat"],
    image: "https://placehold.co/600x400/B8722F/ffffff?text=Wheat+Rust",
    symptoms: "Orange-brown powdery pustules on leaves and stems, premature drying of leaves, reduced grain filling and yield loss.",
    treatment: "Spray Propiconazole 25% EC at 1ml/litre water at the first sign of infection. Repeat after 15 days for severe cases.",
    prevention: "Use rust-resistant wheat varieties, avoid late sowing, ensure proper field spacing for air circulation.",
  },
  {
    _id: "3",
    name: "Bacterial Leaf Blight",
    type: "bacteria",
    affectedCrops: ["Paddy (Rice)"],
    image: "https://placehold.co/600x400/8B6F47/ffffff?text=Leaf+Blight",
    symptoms: "Water-soaked streaks on leaf margins turning yellow then white, wilting of seedlings, drying of entire leaves in severe cases.",
    treatment: "Spray Copper Oxychloride 50% WP at 2.5g/litre water. Drain excess water from fields to reduce humidity.",
    prevention: "Use certified disease-free seeds, avoid excess nitrogen, maintain proper field drainage.",
  },
  {
    _id: "4",
    name: "Yellow Mosaic Virus",
    type: "virus",
    affectedCrops: ["Moong (Green Gram)", "Soybean"],
    image: "https://placehold.co/600x400/A8A832/ffffff?text=Mosaic+Virus",
    symptoms: "Irregular yellow and green mosaic patches on leaves, stunted growth, reduced pod formation and yield.",
    treatment: "Spray Imidacloprid to control whitefly (the carrier insect). Remove and destroy severely infected plants.",
    prevention: "Use resistant varieties, control whitefly population early, avoid planting near infected fields.",
  },
  {
    _id: "5",
    name: "Parthenium Weed",
    type: "weed",
    affectedCrops: ["Various field crops"],
    image: "https://placehold.co/600x400/6B8E23/ffffff?text=Parthenium",
    symptoms: "Fast-spreading white-flowered weed competing aggressively for nutrients, water, and sunlight with main crop.",
    treatment: "Spray Glyphosate 41% SL at 5ml/litre water before flowering stage. Manual uprooting also effective for small areas.",
    prevention: "Clear field borders regularly, avoid using contaminated farm equipment, remove weeds before they flower and seed.",
  },
  {
    _id: "6",
    name: "Pod Borer",
    type: "insect",
    affectedCrops: ["Chana", "Moong (Green Gram)"],
    image: "https://placehold.co/600x400/C9874F/ffffff?text=Pod+Borer",
    symptoms: "Circular holes in pods, larvae feeding inside pods, damaged or hollowed-out seeds reducing marketable yield.",
    treatment: "Spray Chlorantraniliprole 18.5% SC at 0.3ml/litre water during early pod formation stage.",
    prevention: "Use pheromone traps for early detection, intercrop with marigold to repel pests naturally.",
  },
];