// dummy schemes, matches the Scheme schema (title, description, eligibility, benefits, applicationLink, lastDate, category)

export const mockSchemes = [
  {
    _id: "1",
    title: "PM-KISAN",
    category: "subsidy",
    description: "Direct income support scheme providing financial assistance to all landholding farmer families across the country.",
    eligibility: "All landholding farmer families with cultivable land, subject to certain exclusion criteria (income tax payers, government employees, etc.)",
    benefits: "₹6,000 per year, paid in 3 equal installments of ₹2,000 directly to bank accounts.",
    applicationLink: "https://pmkisan.gov.in",
    lastDate: "2026-12-31",
  },
  {
    _id: "2",
    title: "PM Fasal Bima Yojana",
    category: "insurance",
    description: "Crop insurance scheme providing financial support to farmers in case of crop failure due to natural calamities, pests, or diseases.",
    eligibility: "All farmers including sharecroppers and tenant farmers growing notified crops in notified areas.",
    benefits: "Insurance coverage and financial support in case of crop loss, premium as low as 2% for kharif and 1.5% for rabi crops.",
    applicationLink: "https://pmfby.gov.in",
    lastDate: "2026-07-31",
  },
  {
    _id: "3",
    title: "Soil Health Card Scheme",
    category: "other",
    description: "Provides farmers with soil health cards containing crop-wise recommendations of nutrients and fertilizers needed for their farms.",
    eligibility: "All farmers with agricultural landholding, regardless of size.",
    benefits: "Free soil testing every 2 years, personalized fertilizer recommendations to improve productivity and reduce input costs.",
    applicationLink: "https://soilhealth.dac.gov.in",
    lastDate: null,
  },
  {
    _id: "4",
    title: "Kisan Credit Card",
    category: "loan",
    description: "Provides farmers with affordable credit for agricultural needs including crop production, post-harvest expenses, and farm equipment.",
    eligibility: "All farmers, including tenant farmers, sharecroppers, and self-help group members.",
    benefits: "Loans at lower interest rates (as low as 4% with timely repayment), flexible repayment aligned with harvest cycles.",
    applicationLink: "https://www.india.gov.in/kisan-credit-card-scheme",
    lastDate: null,
  },
  {
    _id: "5",
    title: "Rashtriya Krishi Vikas Yojana",
    category: "training",
    description: "Supports states in adopting holistic agricultural development practices through training, modern farming techniques, and infrastructure.",
    eligibility: "Available to farmers through state government agriculture departments; no individual application required.",
    benefits: "Access to training programs, demonstration farms, and modern equipment subsidies through state-led projects.",
    applicationLink: "https://rkvy.nic.in",
    lastDate: null,
  },
];